In [ ]:
import tweepy
import pandas as pd
import re, string
#!pip install torch
#!pip install inltk 


In [ ]:
#pip install tweepy


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# all 4 authentication keys to access twitter API
# to connect as OAth handler or jump serever / twitters  proxy server
consumer_key = "Thed3X13qmABa9KozGLcCwyQf"
consumer_sec = "uR0o9dlmEQPbkIXTl0SnNgj1yS5YJ0XA7fgppkQxRAMCtxOJGl"


# from proxy server we need to connect
access_token = "1387289012662984708-4aSIsJa9jb59T5tbxDbcwS47PktbZ0"
access_token_sec = "UvfCdeo1tEQMK1LXRze8efXhJgAMOe4T8G2767DsQXr8y"

In [ ]:
# connect to jump server of twitter #authenticating the secret code - that I am a valid user of a development account of twitter 
auth = tweepy.OAuthHandler(consumer_key,consumer_sec) #.OAuthHandler is a function that helps to authenticate the consumer key and consumer secret codes above. 
                                                      #We only need consumer key and consumer secret for the task at hand. Access key and access secret are required for packages such as 
                                                      # web application, scrapping in web application. Consumer key & consumer secret are mainly used for sentiment analysis, twitter scrapping and tweepy packages.

In [ ]:
# now we can connect from jump server to web server of twitter. in 3rd party API, we reach the twitter server from out network 
auth.set_access_token(access_token,access_token_sec) #to connect to the servers #when we write auth. it is an object. An object is used to command a certain task. In this case, we are commanding to set access token. 
                                                     # .set_access_token is a predefined function of the tweepy package. 
                                                     
                                                  

In [ ]:
#connect to API storage server of twitter
api_connect=tweepy.API(auth) #.API is a predefined function of the tweepy package 


In [ ]:
hashtag= input("What do you want to search about: .") #input function to create user defined variables 
number= input("Please enter the number of tweets you want download: ")
tweet_data=api_connect.search(hashtag,count=number, lang='en')#.search too is a function within the tweepy package, perhaps present in others too

What do you want to search about: .love dhoni
Please enter the number of tweets you want download: 10000


In [ ]:
print (tweet_data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
for tweet in tweet_data:
 print(tweet.text) #.text is a function to parse all data to text format  

RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @TheDhoniEra: And another reason to love MS Dhoni ❤️

@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA
RT @neophyte420: People criticize #Dhoni for not tweeting anythi

In [ ]:
# my_tweet = []
# for tweet in tweet_data:
#  my_tweet.append(tweet.text)#Place all tweets which are in string format into a list called 'my_tweet' 
# final_my_tweet = ['Tweets']+my_tweet #Add a header called 'Tweets' in order to create a column of tweets in a csv file 
# print(final_my_tweet)  

In [ ]:
my_tweet = set()
for tweet in tweet_data:
 my_tweet.add(tweet.text)#Place all tweets which are in string format into a list called 'my_tweet' 
#Add a header called 'Tweets' in order to create a column of tweets in a csv file 

final_my_tweet = ['Tweets']+list(my_tweet)
final_my_tweet

['Tweets',
 "RT @neophyte420: People criticize #Dhoni for not tweeting anything\n\nMeanwhile dhoni's love for country in real : https://t.co/qvxpz8q9Oi",
 'And another reason to love MS Dhoni ❤️\n\n@mahi7781 #MSDhoni  • #WhistlePodu https://t.co/pvPdCNvcty',
 'RT @Shalvi_Rajput07: He is different man ❤️!!Proud to be his fan not a fan but his devotee 💛 \nLove you dher saara Dhoni ❣️',
 'RT @TheDhoniEra: And another reason to love MS Dhoni ❤️\n\n@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/2nJtMUyFdA',
 '@SnowfIowerAnne Bro sorry i love MS DHONI..\nBut i think he said Emma stone 😭',
 '@duniya_se_alag9 You love Sidharth,you love ms dhoni, you love Virat Kohli, you love Ranbir Kapoor. These aren’t assumptions but facts😜🚶\u200d♀️',
 'RT @TheDhoniEra: Never Doubt Captain Dhoni 😌🦁🔥\n\n@MSDhoni • #MSDhoni  • #WhistlePodu https://t.co/z7GMEMAOBY',
 'RT @kukreja_ravii: " Mahi bhai said that he will be the last person to leave the hotel. He wanted every foreign &amp; the Indian players to rea

In [ ]:
tweets_final=[]
def get_normalize(text):
    text = re.sub(r'\&\w*;','',text)
    text = re.sub('@[^\s]+','',text)
    text = re.sub(r'\$\w*','',text)
    text = text.lower()
    text = re.sub("[^a-zA-Z]", " ", text) 
    text = re.sub(r'https?:\/\/.*\/\w*','',text)
    text = re.sub(r'https?:\w*','',text)
    text = re.sub(r'#\w*','',text)
    text = re.sub(r'[' + string.punctuation.replace('@','') + ']+',' ',text)
    text = re.sub(r'\b\w{1,2}\b','',text)
    text = re.sub(r'\s\s+',' ',text)
    text = text.lstrip(' ')
    text = ''.join(c for c in text if c <= '\uFFFF')
    return text
#j = 0
for i in final_my_tweet:
  final_my_tweet=get_normalize(str(i))
  tweets_final.append(final_my_tweet)
 # j = j+1
print(tweets_final)

['tweets', 'people criticize dhoni for not tweeting anything meanwhile dhoni love for country real https qvxpz ', 'and another reason love dhoni msdhoni whistlepodu https pvpdcnvcty', 'different man proud his fan not fan but his devotee love you dher saara dhoni ', 'and another reason love dhoni msdhoni whistlepodu https njtmuyfda', 'bro sorry love dhoni but think said emma stone ', 'you love sidharth you love dhoni you love virat kohli you love ranbir kapoor these aren assumptions but facts ', 'never doubt captain dhoni msdhoni whistlepodu https gmemaoby', 'mahi bhai said that will the last person leave the hotel wanted every foreign the indian players rea ', 'mahibhai said that will the last person leave the hotel wanted foreigners leave first then the indian ', 'the love have for him increases with each passing day dhoni the leader https jgsnz', 'really enjoyed time again with csk love playing cricket india always amazing experience very sad see what ', 'the reason why love delayed 

In [ ]:
b = open('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/ipl_tweets.csv', 'a') #open() is a function for file handling #my_tweets.csv is an argument that creates a csv file #'w' is a mode to overwrite on the created file 
for i in tweets_final:
  b.write(f"{i}\n") #.write is a function that writes each and every string or element from the list on to the created file #(f"{i}\n) is an argument for string formatting #'f' is a keyword 
                    # used for string formatting #{i}: if you want to format a variable within a string, you must use curly brackets. 
                    #here, 'i' is a variable that denotes each element in the list. #\n pushes to go to the next line in the csv file after each element is formatted and written. 
b.close()           #b.close() closes the opened file. 

In [ ]:
import pandas as pd #we import pandas library to be able to work on dataframes in the csv file 
df = pd.read_csv('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/ipl_tweets.csv') 
df

tweets
0     england counties offer host remainder ipl sept...
1     honestly the best recent times most happening ...
2     decision delay his return after the indefinite...
3     ipl group chat discussing who better shaw gill...
4     have all accounts due sudden decrease reach wi...
...                                                 ...
1357  the love have for him increases with each pass...
1358  really enjoyed time again with csk love playin...
1359  the reason why love delayed himself for ranchi...
1360  dhoni because not only about hitting sixes wou...
1361  really enjoyed time again with csk love playin...

[1362 rows x 1 columns]

In [ ]:
data = df
new_data = data.drop_duplicates(subset="tweets") #to drop retweets and repeated rows #subset is a keyword in pandas with column value as "Tweets" to indicate the column with duplicate text
new_data.to_csv('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/ipl5_filtered_data .csv')
new_data

tweets
0     england counties offer host remainder ipl sept...
1     honestly the best recent times most happening ...
2     decision delay his return after the indefinite...
3     ipl group chat discussing who better shaw gill...
4     have all accounts due sudden decrease reach wi...
...                                                 ...
1357  the love have for him increases with each pass...
1358  really enjoyed time again with csk love playin...
1359  the reason why love delayed himself for ranchi...
1360  dhoni because not only about hitting sixes wou...
1361  really enjoyed time again with csk love playin...

[1112 rows x 1 columns]

In [ ]:
# Text pre-processing 
def get_normalize(text):
    text = re.sub(r'\&\w*;','',text)
    text = re.sub('@[^\s]+','',text)
    text = re.sub(r'\$\w*','',text)
    text = text.lower()
    text = re.sub("[^a-zA-Z]", " ", text) 
    text = re.sub(r'https?:\/\/.*\/\w*','',text)
    text = re.sub(r'https?:\w*','',text)
    text = re.sub(r'#\w*','',text)
    text = re.sub(r'[' + string.punctuation.replace('@','') + ']+',' ',text)
    text = re.sub(r'\b\w{1,2}\b','',text)
    text = re.sub(r'\s\s+',' ',text)
    text = text.lstrip(' ')
    text = ''.join(c for c in text if c <= '\uFFFF')
    return text
j = 0
for i in new_data['tweets']:
  new_data.loc[j]=get_normalize(str(i))
  j = j+1
new_data

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



tweets
0     england counties offer host remainder ipl sept...
1     honestly the best recent times most happening ...
2     decision delay his return after the indefinite...
3     ipl group chat discussing who better shaw gill...
4     have all accounts due sudden decrease reach wi...
...                                                 ...
1066  lata knows how sing modi knows how act pose fo...
1067  don rude danny the man happy and got accepted ...
1068  thackeray gov let him run away from maharastra...
1083  can call him trade analyst verified version ra...
1089  don see any centres showing covaxin except cou...

[1331 rows x 1 columns]

In [ ]:
#   0 = negative
#  1 = neutral
#  2 = positive
import pandas as pd
import re, string

import pkg_resources


from textblob import TextBlob

def getSentiment(text):
    testimonial = TextBlob(text)
    sentiment = testimonial.sentiment.polarity
    if sentiment >= -1 and sentiment <= -0.65:
        return 'negative'
    elif sentiment > -0.65 and sentiment <= 0.35:
        return 'neutral'
    else:
        return 'positive'



new_data['sentiment'] = new_data['tweets'].apply(getSentiment)



new_data.to_csv('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/ipl8_filtered_data.csv',sep='\t', index=False)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
new_data

tweets sentiment
0     england counties offer host remainder ipl sept...   neutral
1     honestly the best recent times most happening ...  positive
2     decision delay his return after the indefinite...   neutral
3     ipl group chat discussing who better shaw gill...  positive
4     have all accounts due sudden decrease reach wi...   neutral
...                                                 ...       ...
1066  lata knows how sing modi knows how act pose fo...   neutral
1067  don rude danny the man happy and got accepted ...   neutral
1068  thackeray gov let him run away from maharastra...  negative
1083  can call him trade analyst verified version ra...   neutral
1089  don see any centres showing covaxin except cou...   neutral

[1331 rows x 2 columns]

In [ ]:
ne = len(new_data[new_data['sentiment'] == 'negative'])
n = len(new_data[new_data['sentiment'] == 'neutral'])
p = len(new_data[new_data['sentiment'] == 'positive'])

In [ ]:
import plotly.graph_objects as go
animals=['negative','neutral','positive']

fig = go.Figure([go.Bar(x=animals, y=[ne,n,p])])
fig.show()

In [ ]:
new_data[new_data['sentiment'] == 'negative']

tweets sentiment
38          ipl matches ipl its boring https fscg blxxw  negative
48                                ipl band boring life   negative
124   nigdi yaa felt bad yesterday when loss but csk...  negative
187   onthisday may indian navy dedicated marcos bas...  negative
194   indiannavalhistory onthisday may insabhimanyu ...  negative
...                                                 ...       ...
936                                    hate virat then   negative
938                      except hate and attitude anni   negative
942   since test format turned into icc tournament v...  negative
952            unreal hate chakraborty popa thamla fan   negative
1068  thackeray gov let him run away from maharastra...  negative

[195 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np
import pickle
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Activation, Dense, Dropout
from sklearn.preprocessing import LabelBinarizer
import sklearn.datasets as skds
from pathlib import Path

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/ipl8_filtered_data.csv',sep='\t')
data

tweets sentiment
0     england counties offer host remainder ipl sept...   neutral
1     honestly the best recent times most happening ...  positive
2     decision delay his return after the indefinite...   neutral
3     ipl group chat discussing who better shaw gill...  positive
4     have all accounts due sudden decrease reach wi...   neutral
...                                                 ...       ...
1326  lata knows how sing modi knows how act pose fo...   neutral
1327  don rude danny the man happy and got accepted ...   neutral
1328  thackeray gov let him run away from maharastra...  negative
1329  can call him trade analyst verified version ra...   neutral
1330  don see any centres showing covaxin except cou...   neutral

[1331 rows x 2 columns]

In [ ]:
# lets take 80% data as training and remaining 20% for test.
train_size = int(len(data) * .8)
 
train_posts = data['tweets'][:train_size]
#print(train_posts)
train_tags = data['sentiment'][:train_size]

 
test_posts = data['tweets'][train_size:]
test_tags = data['sentiment'][train_size:]


In [ ]:
# 4 news groups
num_labels = 3
vocab_size = 1500
batch_size = 10
 
# define Tokenizer with Vocab Size
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(train_posts)
 
x_train = tokenizer.texts_to_matrix(train_posts, mode='tfidf')
x_test = tokenizer.texts_to_matrix(test_posts, mode='tfidf')
 
encoder = LabelBinarizer()
encoder.fit(train_tags)
y_train = encoder.transform(train_tags)
y_test = encoder.transform(test_tags)

In [ ]:
model = Sequential()
model.add(Dense(512, input_shape=(vocab_size,)))
model.add(Activation('relu'))
model.add(Dropout(0.3))



model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.3))

#model.add(Dense(128))
#model.add(Activation('relu'))
#model.add(Dropout(0.3))
    

model.add(Dense(units =512, activation ='relu'))
model.add(Dense(units =256, activation ='relu'))
model.add(Dense(units =128, activation ='relu'))
model.add(Dense(units =32, activation ='relu'))
model.add(Dense(units =16, activation ='relu'))
model.add(Dense(units =8, activation ='relu'))
model.add(Dense(units =3, activation ='relu'))




model.add(Dense(num_labels))
model.add(Activation('softmax'))

model.summary()
 
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
 
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=20,
                    verbose=1,
                    validation_split=0.1)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 512)               768512    
_________________________________________________________________
activation_3 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 256)               131328    
_________________________________________________________________
activation_4 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 512)              

In [ ]:
score = model.evaluate(x_test, y_test,
                       batch_size=batch_size, verbose=1)

print('Test accuracy:', score[1])
print(score)
text_labels = encoder.classes_
print(text_labels)
for i in range(10):
    prediction = model.predict(np.array([x_test[i]]))
    predicted_label = text_labels[np.argmax(prediction[0])]
    print(predicted_label)
    print(test_posts.iloc[i])
    print(prediction)
    print('Actual label:' + test_tags.iloc[i])
    print("Predicted label: " + predicted_label)

27/27 [==============================] - 0s 2ms/step - loss: 1.2911 - accuracy: 0.7266
Test accuracy: 0.7265917658805847
[1.2911317348480225, 0.7265917658805847]
['negative' 'neutral' 'positive']
neutral
they both are hate mongers don support either them just that other person https cnoyfjbzlt
[[2.0330932e-19 1.0000000e+00 8.4945349e-12]]
Actual label:neutral
Predicted label: neutral
neutral
waise main bhi keh sakta hoon hate aur fan wars alag rakho you didn like fine respect that 
[[1.9749472e-23 1.0000000e+00 3.4749340e-14]]
Actual label:neutral
Predicted label: neutral
neutral
lata knows how sing modi knows how act pose for pics sachin knows how score gud player but 
[[8.8483654e-10 9.9999535e-01 4.6398686e-06]]
Actual label:neutral
Predicted label: neutral
neutral
don rude danny the man happy and got accepted how bad mood were https thnckuas
[[1.0278568e-05 9.9876404e-01 1.2257068e-03]]
Actual label:neutral
Predicted label: neutral
neutral
thackeray gov let him run away from mahara

In [1]:
type(test_tag)

NameError: ignored

In [ ]:
# creates a HDF5 file 'my_model.h5'
model = model.save('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/IPL_model.h5')
 
# Save Tokenizer i.e. Vocabulary
with open('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/tokenizer_senti.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
# load our saved model
from keras.models import load_model
model = load_model('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/IPL_model.h5')
 
# load tokenizer
tokenizer = Tokenizer()
with open('/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/tokenizer_senti.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)
    
    
encoder.classes_ #LabelBinarizer

array(['negative', 'neutral', 'positive'], dtype='<U8')

In [ ]:
# These are the labels we stored from our training
# The order is very important here.
 
labels = np.array(['negative', 'neutral', 'positive'])
 
test_files = ["/content/drive/MyDrive/twitter_data_scrap_sentimental_classification/senti.txt"]
x_data = []
for t_f in test_files:
    t_f_data = Path(t_f).read_text()
    x_data.append(t_f_data)
 
x_data_series = pd.Series(x_data)
x_tokenized = tokenizer.texts_to_matrix(x_data_series, mode='tfidf')
 
i=0
for x_t in x_tokenized:
    prediction = model.predict(np.array([x_t]))
    predicted_label = labels[np.argmax(prediction[0])]
    print(prediction)
    print("File ->", test_files[i], "Predicted label: " + predicted_label)

[[0.4209852  0.18401465 0.39500013]]
File -> /content/drive/MyDrive/twitter_data_scrap_sentimental_classification/senti.txt Predicted label: negative


In [ ]:
p = []
predicted_percentage = prediction*100
for i in range(3):
  p.append(predicted_percentage[0][i])
p

[42.09852, 18.401464, 39.50001]

In [ ]:
import plotly.graph_objects as go
labels=['negative', 'neutral', 'positive']

fig = go.Figure([go.Bar(x=labels, y=p)])
fig.show()